project:
  type: website
  output-dir: docs

website:
  title: "Michael Thompson-Brusstar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - data.qmd
      - href: blog/index.qmd
        text: Blog

metadata-files:
  - blog/_metadata.yml

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    self-contained: true

editor: visual
