---
title: "Get in loser, we're doing blogs now."
date: 2025-06-13
categories: 
  - introduction
---

I'll keep this quick. 

Blogs are good. I like that there are good people putting their writing out there, and I guess I could set up a Substack or something. But the truth is that while I like the idea of other people finding and reading my work nice, this blog is mostly for me. 

Historically, if I want to figure something out, I write about it. This has been a problem, since when you write for yourself, it doesn't tend to make sense to anyone else. Despite taking me a long time, I do sometimes make some progress in understanding something that is happening now, or 35 years ago, or 60 years ago. However, I rarely do anything with what I've written except stuff it into an Obsidian note. That seems like a waste. 

My first hope is that I'll stick with this "noodling" for my own sake.  In the spirit of noodling, things might be a bit half-baked but hopefully will still be more interesting and more productive than lurking or posting on social media, which is what I waste my time doing currently. 

It is also true that I sometimes figure out something that is worth explaining to someone *else*. I hope to write things those things here too. I'll aim to start by posting something about why I think the study of bureaucracy is interesting and important, and by producing a little digest of what I've been reading as I work. 





