project:
  type: website
  output-dir: docs
website:
  title: "Michael Thompson-Brusstar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - data.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

